#define TK_EOS                           1
#define TK_ID                            2
#define OP_ASSIGN                        3
#define KW_DECL                          4
#define KW_STRUCT                        5
#define TK_L_BRACE                       6
#define TK_R_BRACE                       7
#define KW_INT                           8
#define KW_BOOL                          9
#define KW_CHAR                         10
#define KW_DOUBLE                       11
#define OP_PLUS                         12
#define OP_MINUS                        13
#define OP_MUL                          14
#define OP_DIV                          15
#define OP_MOD                          16
#define OP_POW                          17
#define TK_L_PAR                        18
#define TK_R_PAR                        19
#define LIT_INT                         20
#define LIT_BOOL                        21
#define LIT_CHAR                        22
#define LIT_DOUBLE                      23
#define OP_GT                           24
#define OP_GET                          25
#define OP_LET                          26
#define OP_LT                           27
#define OP_NEQ                          28
#define OP_EQ                           29
#define TK_DOT                          30
#define KW_IF                           31
#define KW_ELSE                         32
#define KW_PRINT                        33
#define KW_FOR                          34
#define KW_WHILE                        35
#define KW_TYPEOF                       36
