#define TK_EOS                           1
#define TK_ID                            2
#define OP_ASSIGN                        3
#define KW_DECL                          4
#define KW_STRUCT                        5
#define TK_L_BRACE                       6
#define TK_R_BRACE                       7
#define KW_INT                           8
#define KW_BOOL                          9
#define KW_CHAR                         10
#define KW_DOUBLE                       11
#define KW_STRING                       12
#define KW_IF                           13
#define TK_L_PAR                        14
#define TK_R_PAR                        15
#define KW_ELSE                         16
#define OP_GT                           17
#define OP_GET                          18
#define OP_LT                           19
#define OP_LET                          20
#define OP_EQ                           21
#define OP_NEQ                          22
#define KW_FOR                          23
#define KW_WHILE                        24
#define KW_PRINT                        25
#define OP_PLUS                         26
#define OP_MINUS                        27
#define OP_MUL                          28
#define OP_DIV                          29
#define OP_MOD                          30
#define OP_POW                          31
#define TK_DOT                          32
#define KW_TYPEOF                       33
#define LIT_INT                         34
#define LIT_BOOL                        35
#define LIT_CHAR                        36
#define LIT_DOUBLE                      37
#define LIT_STRING                      38
