#define TK_EOL                           1
#define KW_FUNC                          2
#define TK_ID                            3
#define TK_LEFT_PAR                      4
#define TK_RIGHT_PAR                     5
#define OP_COMMA                         6
#define KW_WHILE                         7
#define KW_IF                            8
#define KW_ELSE                          9
#define TK_OPEN_BRAKET                  10
#define TK_CLOSE_BRAKET                 11
#define KW_PRINT                        12
#define KW_DEC                          13
#define KW_HEX                          14
#define KW_BIN                          15
#define OP_ASSIGN                       16
#define OP_EQUAL                        17
#define OP_NOT_EQUAL                    18
#define OP_GREATER_THAN                 19
#define OP_LESS_THAN                    20
#define OP_GREATER_OR_EQUAL             21
#define OP_LESS_OR_EQUAL                22
#define OP_ADD                          23
#define OP_SUB                          24
#define OP_MUL                          25
#define OP_DIV                          26
#define TK_NUMBER                       27
