#define TK_EOL                           1
#define OP_PIPE                          2
#define OP_CONCAT                        3
#define TK_LEFT_PAR                      4
#define TK_RIGHT_PAR                     5
#define OP_KLEENE                        6
#define LIT_INT                          7
#define LIT_LETTER                       8
#define LIT_STRING                       9
